### ISSUE TITLE
Draw a single HIPS tile

### ISSUE THREAD

**Issue by cdeil** [adl1995/HIPS-to-Py#3]
@adl1995 - To practice working with HEALPIX / sky & image coordinates and HIPS, my suggestion would be that we use this example as a test case:
http://www.aanda.org/articles/aa/full_html/2015/06/aa26075-15/F4.html

A first milestone would be to try and (rougly) draw the lower panel and a single HIPS tile (e.g. the one labeled 3/450). This is a significant task, it will take you a while, but you will learn a lot (and will be able to re-use the code in the actual hips package).
Roughly the steps are:
- [x] Make a WCS object that roughly corresponds to that sky region (it doesn't matter much which projection you use, you could use CAR or AIT. See http://astropy.readthedocs.io/en/latest/wcs/index.html#building-a-wcs-structure-programmatically for an example.
- [x] Fill a 2-dim Numpy array that represents the image pixels. For now, you can fill with any values you like.
- [x] Plot a sky image and put markers at some positions (e.g. Galactic center) using  http://astropy.readthedocs.io/en/latest/visualization/wcsaxes/index.html
- [x] Compute positions and draw markers for the HIPS tile center and corners.
- [x] Fetch the correct HIPS tile
- [x] Try to draw the tile using an affine projection in image pixel coordinates, where the affine projection is computed from the tile corner positions you drew earlier.

Please start a script and try to do this in the coming days, and ask questions here.
Just to be clear -- this would be hard for me to implement also, I've never done this.
But I think together we can figure this out, and if we get stuck, ask Thomas for help.

**Comment by adl1995** [comment]
In relation to task 4, assuming a (512x512) tile, wouldn't the four corners of the image always be (1,1), (1,512), (512,1), and (512, 512)? If so, will the marker be placed at (256,256)?

**Comment by adl1995** [comment]
I am not able to view the image located here: [http://www.aanda.org/articles/aa/full_html/2015/06/aa26075-15/F4.html](http://www.aanda.org/articles/aa/full_html/2015/06/aa26075-15/F4.html). It requires a Java plugin and it's not supported on my browser. I have tried adding it following [this](http://www.oracle.com/technetwork/java/javase/manual-plugin-install-linux-136395.html) guide, but it isn't working. So, I have used the template values for sky regions provided in the example.

**Comment by cdeil** [comment]
@adl1995 - That image is Figure 4 from https://www.aanda.org/articles/aa/pdf/2015/06/aa26075-15.pdf . I think that paper is open access, so you should be able to see that PDF.

Note that Thomas already put that data here as one of our test / docs example datasets for that package:
https://github.com/hipspy/hips-extra/tree/master/datasets/samples/GLIMPSE360
So you can also fetch that and play with the data without needing the web connection.

**Comment by adl1995** [comment]
@cdeil Okay, I have used the FITS file from `hips-extra` repository. Also, I plotted contours and circles on the image following [this](http://astropy.readthedocs.io/en/latest/visualization/wcsaxes/overlays.html) guide. I made changes to the [Jupyter notebook](https://github.com/adl1995/HIPS-to-Py/blob/master/examples/coord-plot-example.ipynb) you initialized.

Could you please elaborate drawing the tile using affine transformation? Should I combine the tile corner coordinates to compute the image pixel coordinates?

**Comment by cdeil** [comment]
I'm closing this old issue now. This is mostly implemented in the main `hips` package now.
